loki:
  url: "http://10.0.10.200:3100"  # Loki port

prometheus:
  pushgateway_url: "http://10.0.10.200:9091"  # Pushgateway (needs to be installed)
  job_name: "smblogparser"

query:
  query: '{job="sambalogs"}'
  lookback_ms: 300000  # 5 minutes
  limit: 5000
  device: "default"